# Generated by Django 2.2.2 on 2019-07-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_personal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
