# Generated by Django 2.2.3 on 2019-07-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_personal_author'),
        ('personal', '0003_auto_20190719_0603'),
    ]

    operations = [
    ]
